version: '3'
services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-complex
  redis:
    image: 'redis:latest'
    container_name: redis-complex
  nginx:
    container_name: nginx-complex
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:                              # specify build
      dockerfile: Dockerfile.dev
      context: ./server
    container_name: server-complex
    volumes:
      - /app/node_modules               # a command for not try to overwrite this folder
      - ./server:/app                   # see the default documentation for redis & postgres at https://hub.docker.com/
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379                 # default redis port
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - PGPASSWORD=postgres_password
      - PGPORT=5432
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    container_name: client-complex
    volumes:
      - /app/node_modules
      - ./client:/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./worker
    container_name: worker-complex
    volumes:
      - /app/node_modules
      - ./worker:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379